name: GitHub Third Action 
on: 
  push:
    branches:
      - main
jobs:
  runs-on: ubuntu-latest
  deploy:
    - name: Hello World Hi
      run: echo "Hello world"
    - name: Hello World Hello
      run: echo "Hello world 1"
    - name: Hello World you
      run: echo "Hello world 2"
    